TARGET = XP-DSC-BLDC
# TARGET = XP-MC-CTRL-L2

APP_NAME =
XCC_FLAGS = -Os -g -report  -save-temps
USED_MODULES = module_pip module_mii_singlethread


#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
